# https://realm.github.io/SwiftLint/

included:
  - Plugins
  - Source
  - Tests

excluded:
  - Tests/SwiftLintFrameworkTests/Resources

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - indentation_width
  - rule_id
  - switch_case_on_newline
  - force_cast
  - force_try
  - anonymous_argument_in_multiline_closure
  - closure_body_length
  - conditional_returns_on_newline
  - convenience_type
  - force_unwrapping
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - trailing_closure
  - syntactic_sugar
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - empty_collection_literal
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - identical_operands
  - last_where
  - leading_whitespace
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - number_separator
  - operator_usage_whitespace 
  - redundant_nil_coalescing
  - redundant_type_annotation
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - file_name
  - file_name_no_space
  - type_name

disabled_rules:
  - identifier_name
  - line_length
  - return_arrow_whitespace
  - nesting
  - unused_optional_binding
  - todo
  - cyclomatic_complexity
  - inclusive_language
  - function_parameter_count

vertical_whitespace:
  max_empty_lines: 1

attributes:
  always_on_line_above:
    - "@OptionGroup"

large_tuple: 3

number_separator:
  minimum_length: 5

file_name:
  excluded:
    - SwiftSyntax+SwiftLint.swift
    - GeneratedTests.swift
    - TestHelpers.swift
    - Error.swift
    - RxSwiftExtension.swift
  prefix_pattern: ""
  suffix_pattern: "Extension"

function_body_length: 1000
type_body_length: 1000
file_length: 2000
closure_body_length: 700

type_name:
  max_length: 80
  min_length: 2

indentation_width:
  indentation_width: 2
  include_comments: false

private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 1

conditional_returns_on_newline:
  if_only: true

trailing_closure:
  only_single_muted_parameter: true

empty_count:
  severity: warning

shorthand_operator:
  severity: warning

custom_rules:
  rule_id:
    included: Source/SwiftLintFramework/Rules/.+/\w+\.swift
    name: Rule ID
    message: Rule IDs must be all lowercase, snake case and not end with `rule`
    regex: ^\s+identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
    severity: error
  rule_test_function:
    included: Tests/SwiftLintFrameworkTests/RulesTests.swift
    name: Rule Test Function
    message: Rule Test Function mustn't end with `rule`
    regex: func\s*test\w+(r|R)ule\(\)
    severity: error
  print_using:
    regex: 'print\(.*\)'
    message: "Print decrease performance of the app"
    severity: warning
  debug_using:
    regex: 'debug\(.*\)'
    message: "debug decrease performance of the app"
    severity: warning
  convert_to_observer:
    regex: 'asObserver()'
    message: "Are you sure about Observer in here? Usually it's typo for 'asObservable()'"
    severity: warning

unused_import:
  always_keep_imports:
    - SwiftSyntaxBuilder # we can't detect uses of string interpolation of swift syntax nodes
